name: Deploy Website

permissions:
    id-token: write
    contents: read

on:
    push:
        branches:
        - main
        - dev

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::730335220660:role/GitHubActionsDeployRole
                aws-region: us-east-1

            - name: Set environment variables
              run: |
                if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
                  echo "BUCKET=truittjanney-website-prod" >> $GITHUB_ENV
                  echo "DISTRIBUTION_ID=E3UZNF6QBUZVDO" >> $GITHUB_ENV
                else
                  echo "BUCKET=truittjanney-website-dev" >> $GITHUB_ENV
                  echo "DISTRIBUTION_ID=E1P2CB0T9OSWQD" >> $GITHUB_ENV
                fi

            - name: Sync dist directory to S3
              run: |
                aws s3 sync ./dist s3://$BUCKET --delete

            - name: Invalidate CloudFront cache
              run: |
                aws cloudfront create-invalidation \
                --distribution-id $DISTRIBUTION_ID \
                --paths "/*"
